version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    depends_on:
      - mongo-auth
    environment:
      - MONGO_URI=mongodb://mongo-auth:27017/auth

  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo-products
    environment:
      - MONGO_URI=mongodb://mongo-products:27017/products

  order-service:
    build: ./order-service
    ports:
      - "6000:6000"
    depends_on:
      - mongo-orders
    environment:
      - MONGO_URI=mongodb://mongo-orders:27017/orders

  notification-service:
    build: ./notification-service
    ports:
      - "7000:7000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - notification-service

  mongo-auth:
    image: mongo
    container_name: mongo-auth
    ports:
      - "27017:27017"

  mongo-products:
    image: mongo
    container_name: mongo-products
    ports:
      - "27018:27017"

  mongo-orders:
    image: mongo
    container_name: mongo-orders
    ports:
      - "27019:27017"

      